name: Producer SDK Java CI with Maven

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  load-matrix:
    runs-on: ubuntu-latest
    outputs:
      build_jni_matrix: ${{ steps.set-matrix.outputs.build_jni_matrix }}
      unit_test_matrix: ${{ steps.set-matrix.outputs.unit_test_matrix }}
      sample_matrix: ${{ steps.set-matrix.outputs.sample_matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load matrix from YAML
        id: set-matrix
        run: |
          MATRIX=$(yq eval '.matrix | explode(.)' .github/matrix.yaml -o=json)

          BUILD_JNI_MATRIX=$(echo "$MATRIX" | jq -c '{platform: .platform}')
          UNIT_TEST_MATRIX=$(echo "$MATRIX" | jq -c '{platform: .platform, java: .java}')
          SAMPLE_MATRIX=$(echo "$MATRIX" | jq -c '.')

          echo "build_jni_matrix=$BUILD_JNI_MATRIX" >> $GITHUB_OUTPUT
          echo "unit_test_matrix=$UNIT_TEST_MATRIX" >> $GITHUB_OUTPUT
          echo "sample_matrix=$SAMPLE_MATRIX" >> $GITHUB_OUTPUT

  build-jni:
    needs: load-matrix
    strategy:
      matrix: ${{ fromJson(needs.load-matrix.outputs.build_jni_matrix) }}
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}

    env:
      BRANCH_NAME: develop

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      - name: Build JNI (Mac and Linux)
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        run: |
          mkdir build
          cd build
          cmake ..
          make -j

      - name: Build JNI (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          @echo on

          :: Create build directory
          mkdir build || exit /b 1
          cd build || exit /b 1

          :: Run CMake with the correct path
          cmake .. -G "Visual Studio 17 2022" || exit /b 1
          cmake --build . --config Release --verbose || exit /b 1

          :: Move the compiled library to the expected location
          :: Note: Using Visual Studio generator, the output file gets put in Release\KinesisVideoProducerJNI.dll
          :: rather than in the build folder directly
          move Release\KinesisVideoProducerJNI.dll . || exit /b 1

      - name: Upload JNI Library
        uses: actions/upload-artifact@v4
        with:
          name: jni-library-${{ matrix.platform.name }}
          path: |
            build/libKinesisVideoProducerJNI.so
            build/libKinesisVideoProducerJNI.dylib
            build/KinesisVideoProducerJNI.dll
          retention-days: 1

  run-unit-tests:
    needs:
      - load-matrix
      - build-jni
    strategy:
      matrix: ${{ fromJson(needs.load-matrix.outputs.unit_test_matrix) }}
      fail-fast: false

    env:
      TEST_STREAMS_PREFIX: producer-java-${{ matrix.platform.os }}-java-${{ matrix.java }}_
      JNI_FOLDER: ${{ github.workspace }}/jni

    runs-on: ${{ matrix.platform.os }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      - name: Download JNI Library
        uses: actions/download-artifact@v4
        with:
          name: jni-library-${{ matrix.platform.name }}
          path: jni/

      - name: Build with Maven
        run: mvn clean compile assembly:single

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run tests
        run: |
          mvn clean test -DargLine="-Daws.accessKeyId=${AWS_ACCESS_KEY_ID} -Daws.secretKey=${AWS_SECRET_ACCESS_KEY} -Daws.sessionToken=${AWS_SESSION_TOKEN} -Djava.library.path=${JNI_FOLDER} -Dlog4j.configurationFile=log4j2.xml"
        shell: bash

  run-samples:
    needs:
      - load-matrix
      - build-jni
    strategy:
      matrix: ${{ fromJson(needs.load-matrix.outputs.sample_matrix) }}
      fail-fast: false

    env:
      STREAM_NAME: producer-java-${{ matrix.platform.os }}-java-${{ matrix.java }}_${{ matrix.sample }}
      JNI_FOLDER: ${{ github.workspace }}/jni

    runs-on: ${{ matrix.platform.os }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: maven

      - name: Set up Python 3.12
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        working-directory: scripts/python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download JNI Library
        uses: actions/download-artifact@v4
        with:
          name: jni-library-${{ matrix.platform.name }}
          path: jni/

      - name: Build with Maven
        run: mvn clean compile assembly:single

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create the stream (DemoAppMain)
        # This sample needs a pre-created stream: `${NAME}`
        if: ${{ matrix.sample == 'DemoAppMain' }}
        working-directory: scripts
        run: |
          ./prepareStream.sh "$STREAM_NAME"

        shell: bash

      - name: Create the stream (DemoAppCachedInfo)
        # This sample needs 2 pre-created streams: `${NAME}-account-1` and `${NAME}-account-2`
        if: ${{ matrix.sample == 'DemoAppCachedInfo' }}
        working-directory: scripts
        run: |
          ./prepareStream.sh "$STREAM_NAME-account-1"
          ./prepareStream.sh "$STREAM_NAME-account-2"

        shell: bash

      - name: Run the sample
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        run: |
          set +e

          JAR_FILE=$(find target -name '*jar-with-dependencies.jar' | head -n 1)

          if [ -z "$JAR_FILE" ]; then
            echo "Error: JAR file not found!"
            exit 1
          fi

          echo "Using JAR file: $JAR_FILE"
          java -classpath "$JAR_FILE" \
            -Daws.accessKeyId=${AWS_ACCESS_KEY_ID} \
            -Daws.secretKey=${AWS_SECRET_ACCESS_KEY} \
            -Daws.sessionToken=${AWS_SESSION_TOKEN} \
            -Djava.library.path=${JNI_FOLDER} \
            -Dkvs-stream=$STREAM_NAME \
            -Dlog4j.configurationFile=log4j2.xml \
            com.amazonaws.kinesisvideo.demoapp.${{ matrix.sample }} &
          JAVA_PID=$!

          python ./scripts/python/capture_rss_and_cpu.py $JAVA_PID &
          MONITOR_PID=$!

          # Wait for maximum 30 seconds
          TIMEOUT=30
          for ((i=1; i<=TIMEOUT; i++)); do
            if ! kill -0 $JAVA_PID 2>/dev/null; then
              break
            fi
            sleep 1
            if [ $i -eq $TIMEOUT ]; then
              # Time's up, kill the process
              kill -9 $JAVA_PID
            fi
          done

          wait $JAVA_PID
          EXIT_CODE=$?
          wait $MONITOR_PID

          set -e

          # Check if the process was forcefully killed
          if [ $EXIT_CODE -eq 124 ]; then
            echo "Error: Sample application exceeded 30 seconds and was forcefully terminated."
            exit 1
          fi

          # Preserve original exit code
          echo "Process exited with code: $EXIT_CODE"
          exit $EXIT_CODE

        shell: bash

      - name: Run the sample (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          for /f "delims=" %%F in ('dir /b /s target\*jar-with-dependencies.jar') do set JAR_FILE=%%F

          if not defined JAR_FILE (
            echo Error: JAR file not found!
            exit /b 1
          )

          echo Using JAR file: %JAR_FILE%

          timeout /t 30 /nobreak && exit /b 124

          java -classpath "%JAR_FILE%" ^
            -Daws.accessKeyId=%AWS_ACCESS_KEY_ID% ^
            -Daws.secretKey=%AWS_SECRET_ACCESS_KEY% ^
            -Daws.sessionToken=%AWS_SESSION_TOKEN% ^
            -Djava.library.path=%JNI_FOLDER% ^
            -Dkvs-stream=%STREAM_NAME% ^
            -Dlog4j.configurationFile=log4j2.xml ^
            com.amazonaws.kinesisvideo.demoapp.${{ matrix.sample }}

          set EXIT_CODE=%ERRORLEVEL%

          echo Process exited with code: %EXIT_CODE%
          exit /b %EXIT_CODE%

      - name: Generate memory and CPU graph (Mac and Linux)
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        run: |
          DATA_FILE=$(find . -name 'process_*.txt' | head -n 1)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          python ./scripts/python/plot_rss_and_cpu.py "$DATA_FILE" \
            --title "Memory and CPU Usage (${{ matrix.sample }} @ ${COMMIT_HASH})\n${{ matrix.platform.os }}, Java ${{ matrix.java }}" \
            --output "${{ env.STREAM_NAME }}-mem-cpu.png"

        shell: bash

      - name: Upload memory and CPU graph (Mac and Linux)
        if: ${{ runner.os == 'macOS' || runner.os == 'linux' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.STREAM_NAME }}-mem-cpu.png
          path: ${{ env.STREAM_NAME }}-mem-cpu.png
          retention-days: 7
